services:
  tg_bot_creator:
    build: .
    container_name: tg_bot_creator
    env_file: .env
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - ai_serivices_web

networks:
  ai_serivices_web:
    external: true
