"""add_username_to_allowed_chats

Revision ID: cca6cc0631d6
Revises: 8f093713d174
Create Date: 2026-02-14 15:12:41.531395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca6cc0631d6'
down_revision: Union[str, None] = '8f093713d174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed_chats', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowed_chats', 'username')
    # ### end Alembic commands ###
